# GitHub Repository Configuration
# This YAML file defines the complete repository configuration including branch protection
# Applied using: ./scripts/setup-branch-protection.sh

repository:
  name: "KnowShow2"
  description: "Episode Identifier - PGS Subtitle Extraction for AV1 videos"
  
  # Repository settings
  settings:
    visibility: "public"
    has_issues: true
    has_projects: true
    has_wiki: false
    has_downloads: true
    
    # Merge settings
    allow_merge_commit: false
    allow_squash_merge: true
    allow_rebase_merge: true
    allow_auto_merge: false
    delete_branch_on_merge: true
    
    # Security settings
    vulnerability_alerts: true
    
    # Default branch
    default_branch: "main"

# Branch protection rules
branch_protection:
  main:
    # Pull request requirements (modified for solo development)
    required_pull_request_reviews:
      required_approving_review_count: 0  # Allow self-approval for solo dev
      dismiss_stale_reviews: true
      restrict_dismissals: false
      require_code_owner_reviews: false  # Disabled to allow self-approval
      require_last_push_approval: false
    
    # Required status checks - ALL MUST PASS
    required_status_checks:
      strict: true  # Requires branch to be up to date before merging
      contexts:
        - "build-and-test"
        - "verify-setup"
        - "security-scan"
        - "lint-and-format"
        - "docs-check"
    
    # Additional restrictions - ENFORCED
    enforce_admins: false  # Allow admin to bypass in emergencies
    allow_deletions: false  # Cannot delete main branch
    allow_force_pushes: false  # NO force pushes to main
    require_signed_commits: false  # Optional: enable if you use commit signing
    require_conversation_resolution: true  # All PR comments must be resolved
    
    # Push restrictions (empty = no restrictions, PRs still required)
    push_restrictions: []

# Repository labels
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  
  - name: "needs-triage"
    color: "fbca04"
    description: "Needs initial review and categorization"
  
  - name: "workflow-violation"
    color: "b60205"
    description: "Violates project workflow requirements"
  
  - name: "urgent"
    color: "ff0000"
    description: "Requires immediate attention"
  
  - name: "needs-attention"
    color: "ff9500"
    description: "Requires maintainer attention"
  
  - name: "constitution-compliant"
    color: "0e8a16"
    description: "Follows project constitution principles"
  
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

# Repository topics for discoverability
topics:
  - "video-processing"
  - "subtitle-extraction"
  - "pgs"
  - "av1"
  - "episode-identification"
  - "csharp"
  - "dotnet"
  - "cli-tool"
  - "ocr"
  - "ffmpeg"
